# --------------------------------------------------------
# These properties are the local development properties.
#
# Spring boot uses this file when the application is launched
# with the root of the project set as the working directory.
# These properties take precendence over the classpath
# application.yml.
#
# Using gradle from the commandline means the working
# directory is by defaul the project root.
#
# Using Intellij you need to setup your run config so the
# working directory is the project root.
# --------------------------------------------------------
server:
  port: 8089

security:
  basic:
    enabled: "${SECURITY_ENABLED:true}"
  user:
    name: "admin"
    password: "admin"

logging:
  level:
    org:
      opentestsystem:
        ap:
          irs: "debug"
          common: "debug"

spring:
  session:
    enabled: "${SESSION_CLUSTER_ENABLED:true}"
  datasource:
    url: "jdbc:postgresql://localhost:5432/iat"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
    validationQuery: "SELECT 1"
  jpa:
    hibernate:
      ddl-auto: "validate"
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

itembank:
  host: "https://gitlab-dev.smarterbalanced.org"
  accessToken: "${GITLAB_ACCESS_TOKEN}"
  user: "${GITLAB_USER}"
  password: "${GITLAB_PASSWORD}"
  group: "${GITLAB_GROUP}"
  localBaseDir: "${HOME}/ItemBankTMS"
  apiVersion: "/api/v4"
  bankKey: "200"
  systemVersion: "iat-20"
  enabled:
    database: true
  aws:
    endpointUrl: "https://s3.us-east-2.amazonaws.com"
    region: "us-east-2"
    bucketName: "${itembank.group}"
    accessKey: "${IAT_AWS_ACCESS_KEY}"
    secretKey: "${IAT_AWS_ACCESS_SECRET}"


tasks:
  itemCleanupThresholdMillis : "1800000000"
  itemCleanupRunEveryMillis: "1800000000"

---
spring:
  profiles: dev
  datasource:
    url: "jdbc:postgresql://imrt-qa-db.cjqp2fdamfoh.us-east-2.rds.amazonaws.com:5432/iat"
    tomcat:
      max-active: 2

itembank:
  group: "iat-development"