test-package:
  create: >-
    INSERT INTO test_package (id, package_id, locked, is_being_created, test_package_json, message, inserted_by) VALUES
      (:id, :packageId, :locked, :beingCreated, cast(:testPackage AS JSON), :message, :insertedBy)

  findOne: >-
    SELECT id, package_id, locked, is_being_created, test_package_json, message, inserted_date, inserted_by, message
    FROM test_package where id = :id

  findLatestByTestPackageId: >-
    SELECT id, package_id, locked, is_being_created, test_package_json, message, inserted_date, inserted_by, message
    FROM test_package where test_package_id = :testPackageId order by inserted_date desc limit 1;